#!/bin/sh
arg1=$1

mvn clean install

dir=target
jar_name=parkinglot-1.0-SNAPSHOT.jar

jar_path=$dir/$jar_name

if [ -z "$1" ] ; then
        java -jar $jar_path console
        exit 1

else
	java -jar $jar_path file $arg1

fi

